spring:
  datasource:
    # auth 数据源（注意数据库的时区设置 sql: set global time_zone='+8:00'; flush privileges; 即设置数据库时区+8小时）
    auth:
      druid:
        authMapperLocations: classpath:mybatis/mapper/auth/*.xml
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat,wall,slf4j
        initialSize: 3
        maxActive: 20
        maxWait: 60000
        minIdle: 10
        password: ark123
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        url: jdbc:mysql://47.102.144.221:3306/zb-shiro?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        validationQuery: SELECT 1 FROM DUAL
    # base 数据源（注意数据库的时区设置 sql: set global time_zone='+8:00'; flush privileges; 即设置数据库时区+8小时）
    base:
      druid:
        baseMapperLocations: classpath:mybatis/mapper/base/*.xml
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat,wall,slf4j
        initialSize: 5
        maxActive: 20
        maxWait: 60000
        minIdle: 10
        password: ark123
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        url: jdbc:mysql://47.102.144.221:3306/temp?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        validationQuery: SELECT 1 FROM DUAL
    # druid监控
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 1000
        wall:
          config:
            multi-statement-allow: true
      statViewServlet:
        enabled: true
        login-password: root
        login-username: root
        url-pattern: /druid/*
      use-global-data-source-stat: true
      webStatFilter:
        enabled: true
