# 文件上传相关配置
spring:
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 100MB
      # request 携带文件最大大小（一次请求携带文件总大小）
      max-request-size: 1000MB

# 阿里OSS云存储参数配置
storage:
  way: oss
  oss:
    # 访问路径中的Bucket
    bucket: quick-file-serve
    # 外网Endpoint
    endpoint: oss-cn-beijing.aliyuncs.com
    # Region ID
    region_id: cn-beijing
    # 密钥ID
    access_key_id: LTAI5tPh3yDjA8WTwbinGYCD
    # 密钥
    access_key_secret: S3VXnGOPAHafEfjwOj91gSADocBYhB
    # 角色名称
    role_session_name: quick-file-serve
    # 角色ARN
    role_arn: acs:ram::1954506457702280:role/quick-file-serve
    # 存储基础路径
    oss_base_path: /quick
  local:
    # 文件访问容器（用于生成文件访问地址）
    web_host: http://47.102.144.221:80
    # FTP主机地址
    ftp_host: 47.102.144.221
    # FTP连接端口
    ftp_port: 21
    # FTP连接账号
    ftp_username: quick
    # FTP连接密码
    ftp_password: 123456
    # 存储基础路径
    ftp_base_path: /quick

