# 认证服务配置
auth:
  # 认证服务所属系统，不同的项目该参数绝对不可重复
  serve_name: quick
  access_key: 123123
# shiro核心参数 ShiroCoreParameters类
shiro:
  # 是否开启系统权限认证功能
  # 哈希加密迭代次数
  hash_iterations: 2
  # 同一个帐号最大会话数
  enable: true
  # 令牌过期时间（单位：秒）
  token_expiration_time: 3800
  # 加密名称（当前必填:md5，否者需要修改UserController代码）
  hash_algorithm_name: md5
  max_session: 2
  # false顶掉当前登录的用户/true顶掉之前登录的用户
  kickout_after: true
  # 令牌名称
  token_key: "Authorization"
  # 令牌值前缀
  token_value_prefix: "Bearer "
  # 未登录 重定向地址
  no_login: ${request.prefix.auth_server}/tourist/noLogin
  # 没有权限 重定向地址
  no_auth: ${request.prefix.auth_server}/tourist/noAuth
  # 踢出 重定向地址
  kick_out: ${request.prefix.auth_server}/tourist/kickout
  # 设置指定的请求地址，无需进入认证和鉴权
  excludeAuthPathList:
    - ${request.prefix.auth_server}/tourist/**
    - ${request.prefix.log_server}/logback/**
    - ${request.prefix.base_server}/test/**
  # shiro-redis相关参数配置
  shiro-redis:
    host: ${spring.redis.host}:${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database}
    # 在线用户token缓存前缀
    prefix_user_auth: "system_name:shiro:session:"
    # 账号异地在线数量缓存前缀
    prefix_online: "system_name:shiro:online_user:"
    # 其他信息缓存前缀
    prefix_other: "system_name:shiro:"
