# sentinel配置（系统流控规则）
sentinel:
  # 是否启动流控
  enable: false
  flowGrade:
    qps:
      # 配置sentinel阈值类型QPS的单机阈值（即1秒，用户最多访问次数）
      count: 1

spring:
  cloud:
    sentinel:
      transport:
        # Sentinel服务端地址+端口信息
        dashboard: 127.0.0.1:8091
