# 日志服务配置
log:
  # 是否开启服务日志记录 (true:将需要鉴权的接口进行操作记录到日志表)
  enable: true
  # 是否允许通过API接口访问logback服务html日志文件（不安全的操作） 即接口是否对外开放：/logback/{type}/{dateTime}
  accessLogFileEnable: true
  # enable为true时，系统会将鉴权的接口进行日志记录外，同时可以配置特定的接口也进行日志记录
  recordSpecificPathList:
    - path: ${request.prefix.auth_server}/tourist/login
      description: 系统登录
  # 日志文件保存路径
  path: ../log/${spring.application.name}
  # 通过API接口查询日志文件密钥，多个参数使用逗号隔开 （get请求，携带参数 access_key=${access_key} 即可）
  accessKey: F9F09728BBC81DA9
