spring:
  redis:
    host: 47.102.144.221
    password: 123456
    port: 6379
    timeout: PT10S
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: PT10S
        min-idle: 0
